global:
  scrape_interval:     15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "alert.rules.yml"

scrape_configs:

  # Docker container metrics (CPU, memory, network per container)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # EC2 host OS metrics (total CPU, RAM, disk)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Nginx HTTP request metrics (request rate, connections)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
